# Generated by Ginger 5.3.4 on 2024-07-14 12:21

from ginger.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_group_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
    ]
